'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { Star } from 'lucide-react';

export function Testimonials() {
  const testimonials = [
    {
      name: 'Karthik R.',
      role: 'Founder, ShopKart',
      avatar: 'K',
      bg: 'bg-gradient-to-tr from-purple-500 to-indigo-500',
      text: 'MarketMind AI cut my research time by 80%. Now I can focus on what really matters—growing my business revenue!',
    },
    {
      name: 'Priya S.',
      role: 'Digital Marketer',
      avatar: 'P',
      bg: 'bg-gradient-to-tr from-blue-500 to-indigo-500',
      text: 'The ad copy and content ideas generated by MarketMind AI are incredible. Our social engagement has never been higher.',
    },
    {
      name: 'Vikram M.',
      role: 'Growth Hacker',
      avatar: 'V',
      bg: 'bg-gradient-to-tr from-emerald-500 to-teal-500',
      text: 'Finally, an AI assistant specifically built for marketers. Everything I need in one clean, fast workspace!',
    },
  ];

  return (
    <section id="testimonials" className="py-10 md:py-12 bg-white">
      <div className="max-w-[1280px] mx-auto px-4 sm:px-6 lg:px-8 text-center space-y-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 15 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.4, ease: 'easeOut' }}
          className="max-w-xl mx-auto space-y-1.5"
        >
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-purple-100/80 text-purple-700 text-xs font-semibold">
            <span className="w-1.5 h-1.5 rounded-full bg-purple-500" />
            <span>Loved by Marketers</span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-black text-slate-950 tracking-tight">
            What Our Users Say
          </h2>
        </motion.div>

        {/* Testimonials Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-5 text-left">
          {testimonials.map((t, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 15 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: idx * 0.05, ease: 'easeOut' }}
              className="p-5 sm:p-6 rounded-[20px] bg-white border border-slate-200/80 shadow-2xs space-y-4 flex flex-col justify-between hover:shadow-md hover:-translate-y-1 transition-all duration-200"
            >
              <p className="text-xs sm:text-sm text-slate-600 leading-relaxed italic font-medium">
                "{t.text}"
              </p>

              <div className="flex items-center justify-between pt-3 border-t border-slate-100">
                <div className="flex items-center gap-2.5">
                  <div className={`w-8 h-8 rounded-full ${t.bg} text-white font-bold flex items-center justify-center text-xs shadow-2xs`}>
                    {t.avatar}
                  </div>
                  <div>
                    <div className="font-bold text-xs sm:text-sm text-slate-950">{t.name}</div>
                    <div className="text-xs text-slate-400 font-medium">{t.role}</div>
                  </div>
                </div>

                <div className="flex items-center space-x-0.5 text-amber-400">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} className="w-3.5 h-3.5 fill-current" />
                  ))}
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
