'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { Star, Quote } from 'lucide-react';

export function Testimonials() {
  const testimonials = [
    {
      name: 'Karthik R.',
      role: 'Founder, ShopKart',
      avatar: 'K',
      bg: 'bg-gradient-to-tr from-blue-600 to-indigo-600',
      text: 'MarketMind AI cut my research time by 80%. Now I can focus on what really matters—growing my business!',
    },
    {
      name: 'Priya S.',
      role: 'Digital Marketer',
      avatar: 'P',
      bg: 'bg-gradient-to-tr from-purple-600 to-pink-600',
      text: 'The content and ad copies generated by AI are amazing. My engagement has never been this high!',
    },
    {
      name: 'Vikram M.',
      role: 'Growth Hacker',
      avatar: 'V',
      bg: 'bg-gradient-to-tr from-emerald-600 to-teal-600',
      text: 'Finally, an AI tool built for marketers. Everything I need in one place!',
    },
  ];

  return (
    <section id="testimonials" className="py-20 md:py-28 bg-white dark:bg-slate-950 border-t border-slate-200/60 dark:border-slate-800">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center space-y-12">
        {/* Header */}
        <div className="max-w-2xl mx-auto space-y-3">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-blue-50 dark:bg-blue-950/60 border border-blue-200 dark:border-blue-800 text-blue-600 dark:text-blue-400 text-xs font-bold">
            <span>💬 Loved by Marketers</span>
          </div>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">
            What Our Users Say
          </h2>
          <p className="text-sm sm:text-base text-slate-600 dark:text-slate-400">
            Over 1,000+ founders, marketers, and agency owners rely on MarketMind AI daily.
          </p>
        </div>

        {/* Testimonials Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-left">
          {testimonials.map((t, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: idx * 0.1 }}
              whileHover={{ y: -4 }}
              className="p-7 rounded-3xl bg-slate-50/70 dark:bg-slate-900/60 border border-slate-200/80 dark:border-slate-800 shadow-2xs space-y-6 flex flex-col justify-between"
            >
              <div className="space-y-4">
                <Quote className="w-8 h-8 text-blue-500/30" />
                <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed italic font-medium">
                  "{t.text}"
                </p>
              </div>

              <div className="flex items-center justify-between pt-4 border-t border-slate-200/60 dark:border-slate-800">
                <div className="flex items-center gap-3">
                  <div className={`w-10 h-10 rounded-full ${t.bg} text-white font-bold flex items-center justify-center text-sm shadow-xs`}>
                    {t.avatar}
                  </div>
                  <div>
                    <div className="font-bold text-sm text-slate-900 dark:text-white">{t.name}</div>
                    <div className="text-xs text-slate-500 dark:text-slate-400">{t.role}</div>
                  </div>
                </div>

                <div className="flex items-center space-x-0.5 text-amber-400">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} className="w-3.5 h-3.5 fill-current" />
                  ))}
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
